version: '3.9'
services:
  postgres:
    image: postgres:13
    container_name: 'postgres'
    hostname: 'postgres'
    restart: 'always'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'prisma'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  server:
    build: .
    container_name: 'server'
    restart: 'always'
    depends_on:
      - postgres
    ports:
      - '5000:5000'
volumes:
  postgres:
