version: "3.9"
services:
  postgres:
    image: postgres:13
    container_name: "postgres"
    restart: "always"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "prisma"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - "postgres:/var/lib/postgresql/data"
volumes:
  postgres:
